import javax.swing.*;
import javax.swing.plaf.TextUI;
import javax.swing.text.JTextComponent;
import java.awt.*;

public class MusicBar extends Panel {
    Button play;
    Button pause;
    Button stop;
    Button next;
    Button previous;
    Label songName=new Label("sozngName",3);
    Label artistName=new Label("ArtistName",3);
    Label album=new Label("AlbumName",3);
    Label icon=new Label(3);
    JProgressBar progressBar;
    public MusicBar() {
        super(3);
        this.setLayout(new BorderLayout());
        Panel info=new Panel(3);
        info.setLayout(new GridLayout(3,1));
        info.add(songName);
        info.add(artistName);
        info.add(album);
        icon.setIcon(new ImageIcon("plus.png"));
        Panel image=new Panel(3);
        image.add(icon);
        Panel bottom=new Panel(3);
        bottom.setLayout(new GridLayout(1,5));
        progressBar=new JProgressBar();
        progressBar.setValue(54);
        progressBar.setStringPainted(false);
//        progressBar.setPreferredSize(new Dimension(300,10));
        Panel top=new Panel(3);
        top.add(progressBar);
        this.add(info,BorderLayout.WEST);
        play = new Button(3);
        pause = new Button(3);
        stop = new Button(3);
        next = new Button(3);
        previous = new Button(3);
//        play.setBorder(BorderFactory.createEmptyBorder());
//        pause.setBorder(BorderFactory.createEmptyBorder());
//        previous.setBorder(BorderFactory.createEmptyBorder());
//        next.setBorder(BorderFactory.createEmptyBorder());
//        stop.setBorder(BorderFactory.createEmptyBorder());
        play.setIcon(new ImageIcon("img\\play.png"));
        pause.setIcon(new ImageIcon("img\\pause.png"));
        stop.setIcon(new ImageIcon("img\\stop.png"));
        previous.setIcon(new ImageIcon("img\\next.png"));
        next.setIcon(new ImageIcon("forward.png"));
        bottom.add(previous);
        bottom.add(pause);
        bottom.add(play);
        bottom.add(stop);
        bottom.add(next);
        Panel keke=new Panel(3);
        keke.setLayout(new GridLayout(2,1));
        keke.add(top);
        keke.add(bottom);
        bottom.setBackground(dark3);
        this.add(image,BorderLayout.CENTER);
        this.add(keke);
        this.add(info,BorderLayout.WEST);
    }
}
